name = "gleambox"
version = "0.0.1"

description = "WIP mbox parser in Gleam"
licences = ["LGPL-3.0-only"]
repository = { type = "github", user = "bhankas", repo = "gleammbox" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.36"
simplifile = "~> 1.5"

[dev-dependencies]
gleeunit = "~> 1.0"
