name = "gleambox"
version = "0.0."

description = "WIP mbox parser in Gleam"
licences = ["LGPL-3.0-only"]
repository = { type = "forgejo",   host = "git.bhankas.org", user = "payas", repo = "gleambox" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
simplifile = ">= 2.0.0"
birl = ">= 1.6.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
