name = "gleambox"
version = "0.0.4"

description = "WIP mbox parser in Gleam"
licences = ["LGPL-3.0-only"]
repository = { type = "forgejo",   host = "git.bhankas.org", user = "payas", repo = "gleambox" }

[dependencies]
gleam_stdlib = "~> 0.36"
simplifile = "~> 1.5"

[dev-dependencies]
gleeunit = "~> 1.0"
